# Generated by Django 4.0.8 on 2022-12-31 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'books', 'verbose_name_plural': 'books'},
        ),
    ]
